#!/usr/bin/env node
const fs = require('fs');

const messageFile = process.argv[2];
const message = fs.readFileSync(messageFile, 'utf-8');
const maxLength = 72;
const red = '\x1b[31m';
const yellow = '\x1b[33m';
const green = '\x1b[32m';
const resetColor = '\x1b[0m';

if (message.length > maxLength) {
  console.log(`${red}[FAILED] ${yellow}Your commit message exceeds the maximum length of ${green}${maxLength}${yellow} characters. Its length is ${red}${message.length}${yellow} characters.${resetColor}`);
  process.exit(1);
}
